name = "vibrating_rectangles"
description = "Vibrating Rectangles in Ada for Rosetta Code"
version = "0.1.0-dev"

authors = ["John Perry"]
maintainers = ["John Perry <devotus@yahoo.com>"]
maintainers-logins = ["johnperry-math"]
licenses = "CC-PDDC"
website = ""
tags = ["rosetta", "code", "ada", "vibrating", "rectangles"]

executables = ["vibrating_rectangles"]

[[depends-on]]
rasters = "~0.1.0-dev"

[[pins]]
rasters = { path = "../../rasters" }
